service:
  dm_api_account: "http://5.63.153.31:5051"
  mailhog: "http://5.63.153.31:5025"

user:
  login: 'katya_1_caef2a'
  password: 'Qwerty123!'

telegram:
  chat_id: '738228256'
  token: '7301569682:AAG4PKc2ketQlNwjlnYVyn4YYrAL01tGawk'