name: Python Tests

on: [push, pull_request]

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  test:
    name: Python tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=$(dirname $(readlink -f $(which java)))" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          export JAVA_HOME=$JAVA_HOME
          pytest ./tests --alluredir=allure-results --disable-warnings
        continue-on-error: true

      - name: Generate Swagger Coverage Report
        if: ${{ always() }}
        run: |
          java -cp "venv/lib/python3.10/site-packages/swagger_coverage_py/swagger-coverage-commandline/lib/*" \
          com.github.viclovsky.swagger.coverage.CommandLine \
          -s swagger-doc-dm-api-account.json \
          -i swagger-coverage-output \
          -c swagger-coverage-config-dm-api-account.json

      - name: Move swagger report to bot directory
        if: ${{ always() }}
        run: |
          mv swagger-coverage-dm-api-account.html packages/notifier/

      - name: Run Coverage Bot
        if: ${{ always() }}
        run: |
          python -m packages.notifier.bot

      - name: Archive allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 1


  publish-report:
    runs-on: ubuntu-latest
    needs: generate-report
    name: Publish report
    steps:
      - uses: actions/checkout@v4
      - name: Download site report
        uses: actions/download-artifact@v4
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - run: echo 'https://ekaterinavolynkina.github.io/dm_api_tests/'